"""Add evergreen_sources and content_reservoir tables

Revision ID: 27e9da1c2dc4
Revises: 41f3ad317c8b
Create Date: 2025-12-22 17:24:18.812936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27e9da1c2dc4'
down_revision: Union[str, Sequence[str], None] = '41f3ad317c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rejected_content_phase_time'), table_name='rejected_content')
    op.drop_index(op.f('ix_rejected_content_reasons_gin'), table_name='rejected_content', postgresql_using='gin')
    op.drop_index(op.f('ix_rejected_content_trace'), table_name='rejected_content')
    op.drop_table('rejected_content')
    op.drop_index(op.f('ix_raw_ingest_batch'), table_name='raw_ingest', postgresql_where='(batch_id IS NOT NULL)')
    op.drop_index(op.f('ix_raw_ingest_metadata_gin'), table_name='raw_ingest', postgresql_using='gin')
    op.drop_index(op.f('ix_raw_ingest_source_time'), table_name='raw_ingest')
    op.drop_index(op.f('ix_raw_ingest_status_active'), table_name='raw_ingest', postgresql_where="(status = ANY (ARRAY['PENDING'::ingeststatus, 'PROCESSING'::ingeststatus]))")
    op.drop_index(op.f('ix_raw_ingest_trace'), table_name='raw_ingest')
    op.drop_index(op.f('uq_raw_ingest_content_hash'), table_name='raw_ingest', postgresql_where='(content_hash IS NOT NULL)')
    op.drop_table('raw_ingest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_ingest',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', postgresql.ENUM('REDDIT', 'TWITTER', 'PUBMED', 'GOOGLE_SCHOLAR', 'YOUTUBE', 'BOOK', 'BLOG', 'MANUAL', 'COMPETITOR', name='sourcetype'), autoincrement=False, nullable=False),
    sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_identifier', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('raw_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'PASSED', 'REJECTED', 'ERROR', name='ingeststatus'), autoincrement=False, nullable=False),
    sa.Column('batch_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('ingested_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('content_hash', sa.VARCHAR(), sa.Computed('md5((raw_content)::text)', persisted=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='raw_ingest_pkey'),
    sa.UniqueConstraint('source_type', 'source_identifier', name='uq_raw_ingest_source_identifier', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('uq_raw_ingest_content_hash'), 'raw_ingest', ['content_hash'], unique=True, postgresql_where='(content_hash IS NOT NULL)')
    op.create_index(op.f('ix_raw_ingest_trace'), 'raw_ingest', ['trace_id'], unique=False)
    op.create_index(op.f('ix_raw_ingest_status_active'), 'raw_ingest', ['status'], unique=False, postgresql_where="(status = ANY (ARRAY['PENDING'::ingeststatus, 'PROCESSING'::ingeststatus]))")
    op.create_index(op.f('ix_raw_ingest_source_time'), 'raw_ingest', ['source_type', 'ingested_at'], unique=False)
    op.create_index(op.f('ix_raw_ingest_metadata_gin'), 'raw_ingest', ['raw_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_raw_ingest_batch'), 'raw_ingest', ['batch_id'], unique=False, postgresql_where='(batch_id IS NOT NULL)')
    op.create_table('rejected_content',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('trace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('raw_ingest_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rejection_phase', postgresql.ENUM('PRE_FILTER', 'CLASSIFICATION', 'STRATEGY', 'QA', name='rejectionphase'), autoincrement=False, nullable=False),
    sa.Column('rejection_reasons', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('content_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('rejected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('rejected_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['raw_ingest_id'], ['raw_ingest.id'], name=op.f('rejected_content_raw_ingest_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('rejected_content_pkey'))
    )
    op.create_index(op.f('ix_rejected_content_trace'), 'rejected_content', ['trace_id'], unique=False)
    op.create_index(op.f('ix_rejected_content_reasons_gin'), 'rejected_content', ['rejection_reasons'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_rejected_content_phase_time'), 'rejected_content', ['rejection_phase', 'rejected_at'], unique=False)
    # ### end Alembic commands ###
