"""
Markdown file exporter.

Writes delivery briefs to local filesystem.
"""

import logging
from pathlib import Path
from typing import List

from app.delivery.schemas import DeliveryBrief, WeekPackage

logger = logging.getLogger(__name__)

# Output directory at project root (outside app/)
# This file is at: app/delivery/exporters/markdown_exporter.py
# Project root is 3 levels up
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
OUTPUT_BASE_DIR = PROJECT_ROOT / "content_output"


class MarkdownExporter:
    """Export delivery briefs as Markdown files."""

    def __init__(self, base_dir: Path = OUTPUT_BASE_DIR):
        self.base_dir = base_dir

    def export_week(self, package: WeekPackage) -> List[str]:
        """
        Export a full week's briefs to Markdown files.

        Args:
            package: WeekPackage containing all briefs

        Returns:
            List of created file paths
        """
        # Create week directory
        week_dir = self.base_dir / f"week_{package.week_number:02d}_{package.week_year}"
        week_dir.mkdir(parents=True, exist_ok=True)

        # Create raw JSON subdirectory
        raw_dir = week_dir / "_raw_json"
        raw_dir.mkdir(exist_ok=True)

        created_files: List[str] = []

        # Export individual briefs
        for brief in package.briefs:
            # Write Markdown file
            md_path = week_dir / brief.filename
            md_content = self._build_full_markdown(brief)
            md_path.write_text(md_content, encoding="utf-8")
            created_files.append(str(md_path))

            logger.debug(f"Exported: {md_path}")

        # Export week overview
        overview_path = week_dir / "_WEEK_OVERVIEW.md"
        overview_content = self._build_week_overview(package)
        overview_path.write_text(overview_content, encoding="utf-8")
        created_files.append(str(overview_path))

        logger.info(f"Exported {len(package.briefs)} briefs to {week_dir}")

        return created_files

    def _build_full_markdown(self, brief: DeliveryBrief) -> str:
        """Build complete Markdown file content."""
        return f"""{brief.content_markdown}

---

_Generated by Prismatic Engine | {brief.generated_at.strftime("%Y-%m-%d %H:%M UTC")}_
"""

    def _build_week_overview(self, package: WeekPackage) -> str:
        """Build the week overview Markdown."""
        # Build schedule table
        schedule_rows = []
        for brief in sorted(package.briefs, key=lambda b: b.slot_number):
            time_str = (
                brief.scheduled_time.strftime("%I:%M %p")
                if brief.scheduled_time
                else "TBD"
            )
            quality = brief.quality_scores.average
            quality_indicator = "✅" if brief.quality_scores.passed_all else "⚠️"

            schedule_rows.append(
                f"| {brief.slot_number} | {brief.day_of_week.title()} | {time_str} | "
                f"{brief.format_type} | {brief.pillar} | {quality:.1f} {quality_indicator} |"
            )

        schedule_table = "\n".join(schedule_rows)

        return f"""# 📅 Week {package.week_number}, {package.week_year} — Content Overview

**Period:** {package.start_date} to {package.end_date}

---

## 📊 Summary

| Metric | Value |
|--------|-------|
| **Total Posts** | {package.total_items} |
| **Reels** | {package.reels_count} |
| **Carousels** | {package.carousels_count} |
| **Quotes** | {package.quotes_count} |
| **Avg Quality** | {package.avg_quality_score:.1f}/10 |
| **Needs Attention** | {package.items_needing_attention} |

---

## 📆 Schedule

| # | Day | Time | Format | Pillar | Quality |
|---|-----|------|--------|--------|---------|
{schedule_table}

---

## 📁 Files in This Package

| File | Format | Pillar |
|------|--------|--------|
{self._build_file_list(package.briefs)}

---

## ⚠️ Items Needing Attention

{self._build_attention_list(package.briefs)}

---

_Generated by Prismatic Engine Delivery Agent_
"""

    def _build_file_list(self, briefs: List[DeliveryBrief]) -> str:
        """Build file list table rows."""
        rows = []
        for brief in sorted(briefs, key=lambda b: b.slot_number):
            rows.append(
                f"| [{brief.filename}](./{brief.filename}) | {brief.format_type} | {brief.pillar} |"
            )
        return "\n".join(rows)

    def _build_attention_list(self, briefs: List[DeliveryBrief]) -> str:
        """Build list of items that need attention."""
        attention_items = [b for b in briefs if not b.quality_scores.passed_all]

        if not attention_items:
            return "_None — all items passed quality thresholds!_ ✅"

        lines = []
        for brief in attention_items:
            issues = []
            if brief.quality_scores.ai_voice_risk < 7:
                issues.append(f"AI Voice Risk: {brief.quality_scores.ai_voice_risk}/10")
            if brief.quality_scores.scroll_stop_power < 6:
                issues.append(
                    f"Scroll Stop: {brief.quality_scores.scroll_stop_power}/10"
                )
            if brief.quality_scores.share_impulse < 6:
                issues.append(f"Share Impulse: {brief.quality_scores.share_impulse}/10")

            lines.append(f"- **{brief.filename}**: {', '.join(issues)}")

        return "\n".join(lines)
